version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rocket_db
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    container_name: postgres
